name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
    - uses: actions/checkout@v3
    - name: Log in to Docker Hub
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: List ANSIBLE directory contents
      run: ls -R ./ANSIBLE
    - name: Check playbook file
      run: ls -al ./ANSIBLE/playbook.yml
    - name: Build the image
      run: |
        cd Application
        docker build -t surusuraj200021/suru:node .
    - name: push to dockerhub
      run: docker push surusuraj200021/suru:node
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Terraform Init
      run: terraform init
      working-directory: STEP-1
    - name: Terraform Plan
      run: terraform plan
      working-directory: STEP-1
    - name: Terraform Apply
      run: terraform apply -input=false -auto-approve 
      working-directory: STEP-1
    - name: Terraform Output public-ip
      run: |
        export public=$(terraform output -raw public_ip)
        terraform output -raw public_ip
      working-directory: STEP-1
    - name: Terraform Output private-ip
      run: |
        export private=$(terraform output -raw private_ip)
        terraform output -raw private_ip
      working-directory: STEP-1
    - name: Instance ID
      run: |
        export instance=$(terraform output -raw instance_id)
        terraform output -raw instance_id
      working-directory: STEP-1
    - name: Run playbook
      uses: dawidd6/action-ansible-playbook@v2
      run: |
        cd ANSIBLE
        ansible-playbook -i inventory.yml playbook.yml
      env:
        TERRAFORM_CLI_PATH: /home/runner/work/_temp/684d1336-9143-4fe2-880f-a0bd364942c3
        AWS_DEFAULT_REGION: us-east-1
        AWS_REGION: us-east-1
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - name: Terraform Destroy
      run: terraform destroy -auto-approve
      if: failure() || success()
      working-directory: STEP-1