name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: my-env
    steps:
    - uses: actions/checkout@v3

    - name: Get public IP from Terraform
      id: get-public-ip
      run: |
        terraform output -raw public_ip > $GITHUB_ENV.public_ip
      working-directory: STEP-1

    - name: Use Node.js
      uses: actions/setup-node@v3

    - uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build the image
      run: |
        cd Application
        docker build -t surusuraj200021/suru:node .

    - name: Push to Docker Hub
      run: docker push surusuraj200021/suru:node

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Terraform Init
      run: terraform init
      working-directory: STEP-1

    - name: Terraform Plan
      run: terraform plan
      working-directory: STEP-1

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: STEP-1

    - name: Terraform Output public-ip
      run: |
        export public=$(terraform output -raw public_ip)
        terraform output -raw public_ip
      working-directory: STEP-1
    - name: Terraform Output private-ip
      run: |
        export private=$(terraform output -raw private_ip)
        terraform output -raw private_ip
      working-directory: STEP-1
    - name: Instance ID
      run: |
        export instance=$(terraform output -raw instance_id)
        terraform output -raw instance_id
      working-directory: STEP-1
    - name: Copy the file
      run: |
        cd STEP-1
        chmod 400 capstone.pem
        cd -
        cp STEP-1/capstone.pem ANSIBLE/
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install Ansible
      run: pip install ansible
    - name: Create Ansible Inventory
      run: |
        echo "all:" >> ANSIBLE/inventory.yml
        echo "  hosts:" >> ANSIBLE/inventory.yml
        echo "    capstone:" >> ANSIBLE/inventory.yml
        echo "      ansible_host: $public" >> ANSIBLE/inventory.yml
        echo "      ansible_user: ubuntu" >> ANSIBLE/inventory.yml
        echo "      ansible_ssh_private_key_file: capstone.pem" >> ANSIBLE/inventory.yml
    - name: CAT
      run: cat ANSIBLE/inventory.yml
  
    - name: PING
      run: |
        cd ANSIBLE
        ansible all -m ping -i ANSIBLE/inventory.yml

    - name: Playbook
      run: |
        cd ANSIBLE
        ansible-playbook -i inventory.yml playbook.yml

    - name: Terraform Destroy
      run: terraform destroy -auto-approve
      if: failure() || success()
      working-directory: STEP-1
