# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
    - name: Make a Directory
      run: mkdir nodejs
    - name: Present Working Directory
      run: pwd
    - name: Copy the index.js file to node.js directory
      run: cp index.js nodejs/
    - name: Copy package.json file to node-js directory
      run: cp package.json nodejs/
    - name: Change to nodejs directory
      run: cd nodejs
    - name: Install npm
      run: sudo apt install npm
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag nodejs:$(date +%s)
  
